id: 2531788d-ba5a-4a2e-80f3-9ac2a4255b00
version: 33
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS - Export Tech Support File
description: Export a tech support file (TSF) from PAN-OS.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fcd7fc40-21a2-4db0-810e-08abc1f4ce58
    type: start
    task:
      id: fcd7fc40-21a2-4db0-810e-08abc1f4ce58
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: cbe22d8a-512f-4787-8ecc-2a4c6c75e295
    type: regular
    task:
      id: cbe22d8a-512f-4787-8ecc-2a4c6c75e295
      version: -1
      name: Start TSF export
      description: Exports a tech support file (TSF).
      script: '|||pan-os-export-tech-support-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ignore-outputs:
        simple: "false"
      polling:
        simple: "true"
      using:
        simple: ${PanOSUsing}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d20f3325-9bb4-45ad-8c7d-f53cc8e2d63f
    type: regular
    task:
      id: d20f3325-9bb4-45ad-8c7d-f53cc8e2d63f
      version: -1
      name: Download exported TSF
      description: Downloads a tech support file (TSF) (must run 'pan-os-export-tech-support-file'
        first).
      script: '|||pan-os-download-tech-support-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      ignore-outputs:
        simple: "false"
      job_id:
        simple: ${Panorama.TSF.JobID}
      using:
        simple: ${PanOSUsing}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 5577b0e2-dbbf-454b-846f-4657a8716c78
    type: title
    task:
      id: 5577b0e2-dbbf-454b-846f-4657a8716c78
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 9135d3f2-e1c7-450e-885f-9e2cd1c9a869
    type: condition
    task:
      id: 9135d3f2-e1c7-450e-885f-9e2cd1c9a869
      version: -1
      name: Is PanOSInstance input specified?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.PanOSInstance
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: d06fd3ab-70fe-40c4-8821-bbbe14b73b30
    type: regular
    task:
      id: d06fd3ab-70fe-40c4-8821-bbbe14b73b30
      version: -1
      name: Set name of PAN-OS instance to use
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      key:
        simple: PanOSUsing
      value:
        simple: ${inputs.PanOSInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: fb3126a9-4984-4981-8b3d-2ff9e16abc53
    type: collection
    task:
      id: fb3126a9-4984-4981-8b3d-2ff9e16abc53
      version: -1
      name: Select PAN-OS instance to use
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body: null
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: 'Enter the instance name of the PAN-OS integration instance to use,
            or leave blank to use all instances: '
        required: false
        gridcolumns: []
        defaultrows: []
        type: shortText
        options: []
        optionsarg: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: PAN-OS Instance Selection
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 54eee523-7383-432c-88cb-7d58c709555b
    type: regular
    task:
      id: 54eee523-7383-432c-88cb-7d58c709555b
      version: -1
      name: Set name of PAN-OS instance to use
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      force:
        simple: "true"
      key:
        simple: PanOSUsing
      value:
        simple: ${PAN-OS Instance Selection.Answers.0}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: PanOSInstance
  value: {}
  required: false
  description: Which instance of the PAN-OS integration to use
  playbookInputQuery: null
outputs: []
