id: 2531788d-ba5a-4a2e-80f3-9ac2a4255b00
version: 21
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Export Tech Support File
description: Export a tech support file (TSF) from PAN-OS.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fcd7fc40-21a2-4db0-810e-08abc1f4ce58
    type: start
    task:
      id: fcd7fc40-21a2-4db0-810e-08abc1f4ce58
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 0a2bf7f5-c397-4752-899a-477b2d3798d1
    type: regular
    task:
      id: 0a2bf7f5-c397-4752-899a-477b2d3798d1
      version: -1
      name: Start TSF export
      description: Runs any command supported in the API.
      script: '|||pan-os'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      category:
        simple: tech-support
      extend-context:
        simple: TSFExportJobId=response.result.job
      ignore-outputs:
        simple: "true"
      type:
        simple: export
      using:
        simple: ${inputs.PanOSInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4857f778-04d1-48c8-82d2-f95381b15e28
    type: regular
    task:
      id: 4857f778-04d1-48c8-82d2-f95381b15e28
      version: -1
      name: Retrieve TSF export
      description: Runs any command supported in the API.
      script: '|||pan-os'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      action:
        simple: get
      category:
        simple: tech-support
      extend-context:
        simple: TSFExportJobId=response.result.job
      file_name:
        simple: tsf.tar.gz
      ignore-outputs:
        simple: "true"
      is_file:
        simple: "true"
      job-id:
        simple: ${TSFExportJobId}
      type:
        simple: export
      using:
        simple: ${inputs.PanOSInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 5577b0e2-dbbf-454b-846f-4657a8716c78
    type: title
    task:
      id: 5577b0e2-dbbf-454b-846f-4657a8716c78
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: a87f4ad1-9dc1-4cd1-80ba-f1a9bd9a18b2
    type: regular
    task:
      id: a87f4ad1-9dc1-4cd1-80ba-f1a9bd9a18b2
      version: -1
      name: Poll status of TSF export until complete
      description: Runs any command supported in the API.
      script: '|||pan-os'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      action:
        simple: status
      category:
        simple: tech-support
      extend-context:
        simple: TSFExportJobStatus.id=response.result.job.id::TSFExportJobStatus.status=response.result.job.status
      ignore-outputs:
        simple: "true"
      job-id:
        simple: ${TSFExportJobId}
      polling:
        simple: "true"
      type:
        simple: export
      using:
        simple: ${inputs.PanOSInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: PanOSInstance
  value: {}
  required: true
  description: Which instance of the PAN-OS integration to use
  playbookInputQuery: null
outputs: []
